### ISSUE TITLE
Add Typedefinitions where missing / TS-ignored

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-server#23]
//@ts-ignore
import blobService from 'feathers-blob';
//@ts-ignore
import fs from 'fs-blob-store';
//@ts-ignore
import S3BlobStore from 's3-blob-store';

Let's look through and find any others and get typedefs made.

Look for any other ts-ignore and let's try to remove them and type anything necessary.

**Comment by barankyle** [comment]
What's the preferred way to deal with libraries that don't have types defined?

**Comment by dmitrizagidulin** [comment]
@barankyle from what I understand, it's to cast them as `any`.

**Comment by barankyle** [comment]
Can you give an example? I was trying a few of the rudimentary things I know about TS and that wasn't satisfying the linter.

When I looked this issue up, most seemed to be suggesting making a .d.ts file for each affected library and declaring them as a module.

**Comment by dmitrizagidulin** [comment]
@barankyle ah, my apologies, casting the imports as `any` doesn't actually work.

It's funny, there's obviously a bunch of developers (really, all of them) that run into this problem. As in, there's several discussions about it on the TypeScript repo (like [this one](https://github.com/microsoft/TypeScript/issues/2709)). 
The best thing I saw suggested there was to use an [ambient module declaration](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#shorthand-ambient-module-declarations), so that we don't have to make a `.d.ts` file for _each_ lib we're using.

It basically says we create one file, `declarations.d.ts`, and declare each module in there. So, it's an additional line for each untyped module in our package.json, but that seems to be the least annoying option. (aside from using `ts-ignore`).

**Comment by barankyle** [comment]
That should work too. Is it fine to put that at the top level of the repo?

**Comment by dmitrizagidulin** [comment]
@barankyle I think so, yes.

**Comment by shawticus** [comment]
@barankyle 
What Dmitri said. Also, check out DefinitelyTyped, they hold the @types/ namespace and have types for most common packages -- for ex -- npm install @types/multer
Once we hit a "we can ship this" point I'd like to put on engineer on writing out typedefs for the components we use and looking for TODOs in the code to try to solve, and going through and trying to cast "any" types to their actually type. But for now, //@ts-ignore is very useful.
