### ISSUE TITLE
Search API

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-server#60]
Continuing on Spoke development, integrating Search API to allow Spoke to search for objects from Sketchfab, Google Poly or internal collections. Media search bar should fully integrate with our backend.

We will eventually want to add a search term blacklist -- this will be handled in a separate ticket, but please design in a way where a search term blacklist is not difficult to build in.

**Comment by SaadAhmedSiddiqui** [comment]
@shawticus regarding this issue, reticulum is not saving any media on its own server, instead it is fetching it directly from their respective apis
e.g it is fetching sketchfab from sketchfab site.
But the assets which are uploaded from its own app are saved in reticulum DB

so in order to black list any media we need to save the media object on our own DB too
But there is a problem in that, like we will not be able to get latest updated media if we will not call the direct api and saved on our own DB

**Comment by SaadAhmedSiddiqui** [comment]
but we have one option which is, we can add one layer which will first check that keyword on our db and if that is black list, then we will not call sketchfab api.

But most of the media are not called by their name, we will be able to do this only if we find any media by their name/keyword.

**Comment by shawticus** [comment]
I sounds like the simple solution is to just prevent the search from completing if the search bar contains a blacklisted word. Maybe as the list of returned objects iterates, we can check to see if a blacklisted word is contained in the name or description and skip over rendering that object in the array.

If we need to reference a static object elsewhere for any reason, we have a "static resource" -- when we upload a video to the /upload-video endpoint, it pushes the content to S3 and writes the reference in our database (similar to Reticulum + Nearspark server). Maybe that's useful for the user-upload case.

**Comment by SaadAhmedSiddiqui** [comment]
@shawticus yeah makes sense

**Comment by SaadAhmedSiddiqui** [comment]
@shawmakesmusic can we close this issue?
This is done in this PR #117
